Async http client
keboola/python-http-client pull request #8
Opened 2023-05-25 14:41 UTC by SgtMarmite

Things to discuss:
- naming of retry_status_codes x status_forcelist
- retries x max_retries
- tests coverage
- any missing functions?
- are more examples needed?
- fix httpx version or not?
- currently, the backoff time is calculated like backoff = self.backoff_factor ** retry_attempt and I do not know if that is sufficient.

I do not know if I need to change anything in .github/workflows.

@davidesner @bakobako

2023-10-12 09:43 UTC, SgtMarmite commented
Currently all requests urls are logged into console. This is not intended functionality and I will have to find a way to disable that.

2023-10-27 14:35 UTC, davidesner requested changes

2023-10-27 14:35 UTC, davidesner commented on src/keboola/http_client/async_client.py
> +        for retry_attempt in range(self.retries + 1):
I think this is not needed and the retry can be handled by the same logic as in the normal client using httpx.Retry and by starting the client(session) with retry parameter [see example here](https://scrapeops.io/python-web-scraping-playbook/python-httpx-retry-failed-requests/#retry-failed-requests-using-retry-strategy)

2023-10-27 14:35 UTC, davidesner commented on docs/examples/pokeapi_process_multiple.py
> +    results = await client.process_multiple(jobs)
Is there a way to achieve this without having the `main_async` function `async`? E.g. something like [this](https://bitbucket.org/kds_consulting_team/kds-team.ex-chartmogul/src/53b565568c315cb4ed5cb167d8173945e00ad4e1/src/component.py?at=release%2FKCOFAC-797-optimise-customer_subscriptions#lines-78)  My idea was to have a function, that would run and wait for multiple jobs and just returned all the results (with the disadvantage of having to store all results in memory). Then I would just call something like `results = client.run_multiple_sync()` in my sync function. Is that possible?

Also I somehow dislike the name `process_multiple` what does it do? It actually sends multiple requests (not jobs) and returns list of result futures right? The request is basically the parameters of `_request_raw` http.py equivalent. I think it should be named something like `run_multiple_requests()`. Also I can imagine having equivalent for each method, e.g. `post_multiple`

2025-10-01 15:53 UTC, soustruh commented
Closing this PR in favor of #9

2025-10-01 15:53 UTC, closed without merging