CFT-3212 - Feature/async
keboola/python-http-client pull request #9
Opened 2024-11-07 15:11 UTC by kudj

2025-02-04 08:32 UTC, soustruh requested changes

2025-02-04 08:32 UTC, soustruh commented on .gitignore
> +/docs/examples/test.py
OK, this makes no sense, if anyone used their custom test script, it should be either added for everyone (considering it's in the docs/examples folder?) or just saved elsewhere or treated as a "WIP mess" during local development and ignored – but not in a `.gitignore` way. Creating test.py in the docs/examples folder in the future doesn't seem to be such an improbable scenario, in which case this line here would just cause confusion.

2025-02-04 08:32 UTC, soustruh commented on README.md
> +The AsyncHttpClient provides similar initialization and request methods as the HttpClient.
Use "similar to" please, not "similar as"

2025-02-04 08:32 UTC, soustruh commented on README.md
> +This example demonstrates the default use of the HTTPClient as a base for REST API clients.
AsyncHttpClient

2025-02-04 08:32 UTC, soustruh commented on README.md
> +        response = await self.get('tables', params=params, timeout=5)
I know this is just a docs example, but my eyes simply can't handle mixing quotes like this 🫣 🙈 😁

2025-02-04 08:32 UTC, soustruh commented on docs/examples/pokeapi_async.py
Typo in the file name 😇

2025-02-04 08:32 UTC, soustruh commented on docs/examples/pokeapi_process_multiple.py
> +from typing import List
Please don't use this deprecated class for typing. I also don't understand why this file is type annotated at ONE place, while the previous file has no annotations at all.

2025-02-04 08:32 UTC, soustruh commented on src/keboola/http_client/http.py
> +from requests.packages.urllib3.util.retry import Retry  # noqa
Not needed at all 👀

2025-02-04 08:32 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +    async def get(self, endpoint: Optional[str] = None, **kwargs) -> Dict[str, Any]:
OK, I just checked the rest of this component, I have no words… I miss the basic motivations behinds this renaming/remapping of industry standard Python packages 🤷‍♂️

2025-02-04 08:32 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +            one_reqeust_per_second_amount = float(1 / max_requests_per_second)
Typo and misleading variable name

2025-10-01 16:02 UTC, soustruh commented on .gitignore
> +/docs/examples/test.py
Updated

2025-10-01 16:03 UTC, soustruh commented on README.md
> +The AsyncHttpClient provides similar initialization and request methods as the HttpClient.
Updated

2025-10-01 16:03 UTC, soustruh commented on README.md
> +This example demonstrates the default use of the HTTPClient as a base for REST API clients.
Updated

2025-10-01 16:12 UTC, soustruh commented on README.md
> +        response = await self.get('tables', params=params, timeout=5)
Updated

2025-10-01 16:14 UTC, soustruh commented on docs/examples/poekapi_async.py
Fixed

2025-10-01 16:32 UTC, soustruh commented on docs/examples/pokeapi_process_multiple.py
> +from typing import List
Updated 😌

2025-10-01 16:33 UTC, soustruh commented on src/keboola/http_client/http.py
> +from requests.packages.urllib3.util.retry import Retry  # noqa
Removed

2025-10-01 16:40 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +    async def get(self, endpoint: Optional[str] = None, **kwargs) -> Dict[str, Any]:
Cannot fix this without breaking the components using this library 😿

2025-10-01 16:42 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +            one_reqeust_per_second_amount = float(1 / max_requests_per_second)
Fixed 😀

2025-10-01 16:43 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +            one_reqeust_per_second_amount = float(1 / max_requests_per_second)
The funny thing is, instead of:
```py
        if max_requests_per_second:
            max_request_duration = float(1 / max_requests_per_second)
            self.limiter = AsyncLimiter(1, max_request_duration)
```
there could just be:
```py
        if max_requests_per_second:
            self.limiter = AsyncLimiter(max_requests_per_second, 1)
```

2025-11-18 14:33 UTC, soustruh commented on pyproject.toml
> +name = "keboola.http-client"
This is intentional, the package name at PyPI is dashed anyway.

2025-11-19 13:01 UTC, ZdenekSrotyr approved these changes
LGTM, tests look solid and everything reads well.

2025-11-19 13:02 UTC, soustruh approved these changes
LGTM, the updated client was thoroughly tested in many components already, the test coverage is also sufficient 👍

2025-11-19 13:02 UTC, soustruh commented on README.md
> +It allows you to make asynchronous requests using async/await syntax. To use the AsyncHttpClient, import it from keboola.http_client_async:
Nice catch! 👍

2025-11-19 13:02 UTC, soustruh commented on src/keboola/http_client/http.py
> +Cookie = "dict[str, str] | CookieJar"
Unfortunately, this doesn't work in Python 3.8 which we still support with this component 😐

2025-11-19 13:02 UTC, soustruh commented on src/keboola/http_client/http.py
>              all_pars = {**params, **self._default_params}
Nice catch, but as this line wasn't modified in this PR, I won't touch this now… I will consider a bugfix in the near future though. 👀

2025-11-19 13:02 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +                backoff = self.backoff_factor**retry_attempt
Yeah, not to mention for factors lower than 1, the backoff is actually speeding up instead of backing off. 😁

2025-11-19 13:02 UTC, soustruh commented on README.md
> +
Yep, good catch. 👍 All this logic calls for simplification and cleanup anyway… Let's do this in another minor release after we finally release this. 🙃

2025-11-19 13:02 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +                        raise type(e)(error_msg) from e
Not a problem, we just produce a little less logs for common, easily readable errors

2025-11-19 13:02 UTC, soustruh commented on src/keboola/http_client/async_client.py
> +        all_params = {**self.default_params, **(params or {})}
Nice catch, this code wasn't part of the PR, but it was incorrect and too complicated anyway 🙄 👍

2025-11-19 13:16 UTC, merged